config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

      devise_scope :user do
    authenticated  do
      root 'courses#index'
    end
    unauthenticated do
      root 'home#index', as: :visitors_url
    end
  end 

  resources :categories
  resources :dashboard
  resources :courses do
    get :created, :purchased, :published_unapproved, :pending_review, :latest, :top_rated, :popular, on: :collection
    member do
  		patch :approve
  		patch :disapprove
    end
    resources :subscriptions, only: [:new, :create]
    resources :lessons do
      put :sort
    end
  end

  resources :subscriptions do
    get :my_students, on: :collection
    member do
  		patch :remove_review
    end
  end

  resources :users, only: [:show, :index]

  resources :lessons do
    put :sort
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:show]
  before_action :set_course, only: [:show, :edit, :update, :destroy, :approve, :disapprove]

  def index
    if params[:name]
      @courses = Course.published.approved.where('name ILIKE ?', "%#{params[:name]}%") #case-insensitive
      #@courses = Course.where('name LIKE ?', "%#{params[:name]}%") #case-sensitive
      #@courses = Course.where('LOWER(name) LIKE LOWER(?)', "%#{params[:name]}%") #make lowercase
    else
      @courses = Course.published.approved.all
    end
  end

  def purchased
    @courses = Course.joins(:subscriptions).where(subscriptions: {user: current_user})
    render 'index'
  end
  
  def pending_review
    @courses = Course.joins(:subscriptions).merge(Subscription.pending_review.where(user: current_user))
    render 'index'
  end

  def created
    @courses = Course.where(user_id: current_user.id).order(created_at: :desc)
    render 'index'
  end

  def published_unapproved
    @courses = Course.published.unapproved.order(updated_at: :desc)
    authorize @courses, :approve?
    render 'index'
  end

  def latest
    @courses = Course.all.published.approved.order(created_at: :desc)
    render 'index'
  end

  def top_rated
    @courses = Course.all.published.approved.order(average_rating: :desc, created_at: :desc)
    render 'index'
  end

  def popular
    @courses = Course.all.published.approved.order(subscriptions_count: :desc, created_at: :desc)
    render 'index'
  end

  def approve
    authorize @course, :approve?
		#@event.update_attribute(:status, 'planned')
		@course.update_attribute(:approved, true)
		redirect_to @course, notice: "Course '#{@course.name}' - approved"
  end

  def disapprove
    authorize @course, :approve?
		@course.update_attribute(:approved, false)
		redirect_to @course, alert: "Course '#{@course.name}' - disapproved"
  end

  def show
    authorize @course, :show?
    @lessons = @course.lessons.rank(:row_order)
    @subscriptions = @course.subscriptions.where.not(rating: 0, comment: nil).order(created_at: :desc)
  end

  def new
    @course = Course.new
    authorize @course
  end

  def edit
    authorize @course
  end

  def create
    @course = Course.new(course_params)
    @course.user_id = current_user.id
    authorize @course

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @course
    @course.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :category_id, :short_description, :description, :thumbnail, :language, :duration, :price, :published, :level)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def subscription_buttons(course)
    if current_user
      if course.user == current_user
        link_to "You created this course. View analytics", course_path(course)
      elsif course.subscriptions.where(user: current_user).any?
        link_to course_path(course) do
          "<i class='fa fa-spinner'></i>".html_safe + " " +
          number_to_percentage(course.progress(current_user), precision: 0)
        end
      elsif course.price > 0
        link_to number_to_currency(course.price), new_course_subscription_path(course), class: "btn btn-success"
      else
        link_to new_course_subscription_path(course), class: 'btn btn-md btn-success' do
          number_to_currency(course.price) + " " +
          "Free"
        end
      end
    else
      link_to "Check price", new_course_subscription_path(course), class: 'btn btn-md btn-success'
    end
  end

  def review_buttons(course)
    if current_user
      if course.subscriptions.where(user: current_user).any?
        if course.subscriptions.pending_review.where(user: current_user).any?
          link_to edit_subscription_path(course.subscriptions.pending_review.where(user: current_user).first) do
            "<i class='text-warning fa fa-star'></i>".html_safe + " " +
            "<i class='text-dark fa fa-question'></i>".html_safe + " " +
            "Review"
          end
        else
          "<i class='text-warning fa fa-star'></i>".html_safe + " " +
          "<i class='fa fa-check'></i>".html_safe + " " +
          "Vous avez noté"
        end
      end
    end
  end

  #def action_buttons(course)
  #  if current_user
  #    if course.bought(current_user) && current_user.admin == false
  #      if course.price > 0
  #        link_to "Buy for &euro; ".html_safe+course.price.to_s, new_course_trade_path(course), class: "btn btn-danger"
  #      else
  #        link_to "FREE",course_trades_path(course), method: :post, class: "btn btn-success"
  #      end
  #    else
  #      link_to "Bought", course_path(course), class: "btn btn-success btn"
  #    end
  #  else
  #    if course.price > 0
  #      link_to "Buy for &euro; ".html_safe+course.price.to_s, new_course_trade_path(course), class: "btn btn-danger"
  #    else
  #      link_to "FREE",course_trades_path(course), method: :post, class: "btn btn-success"
  #    end
  #  end
  #end

end

app/views/trash/courses/_course.html.haml
.card
  .card-header
    .fa.fa-graduation-cap
    = link_to course.name, course
  .card-body
    %small= simple_format(course.short_description)
  .card-footer
    .row
      .col-md-6
        .text-warning.fa.fa-star
        %b= course.average_rating
        (#{course.subscriptions_count}
        .fa.fa-user-graduate
        )
  
      .col-md-6.text-right
        .fa.fa-chalkboard-teacher
        = link_to course.user.username, user_path(course.user)

  .card-footer
    .text-center
      /logic in courses_helper.rb
      = subscription_buttons(course)
      .row
      = review_buttons(course)
      /- if course.bought(current_user) == false
      /  Bought
      /- else
      /  Buy

  - if current_user
    - if policy(course).edit?
      .card-footer
        = link_to 'Add a lesson', new_course_lesson_path(course, @lesson), class: 'btn btn-sm btn-primary'
        = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning'
        = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

    - if policy(course).destroy?
      .card-footer
        - if course.published?
          .badge.badge-success
            published
        - else
          .badge.badge-danger
            published
        - if course.approved?
          .badge.badge-success
            approved
        - else
          .badge.badge-danger
            approved
    - if policy(course).approve?
      .card-footer
        - if course.approved?
          = link_to 'Disapprove', disapprove_course_path(course), method: :patch, class: 'btn btn-sm btn-primary'
        - else
          = link_to 'Approve', approve_course_path(course), method: :patch, class: 'btn btn-sm btn-primary'

app/views/trash/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :category, as: :radio_buttons
    = f.input :name, input_html: { autocomplete: 'nope' }
    = f.input :short_description, input_html: { autocomplete: 'nope' }, :input_html => {:rows => 3}
    = f.input :description, input_html: { autocomplete: 'nope' }, :input_html => {:rows => 7}
    = f.input :language, priority: [ "English" ], collection: [ "English", "German", "French", "Russian", "Spanish", "Ukrainian", "Polish"], as: :radio_buttons
    /= f.input :duration
    = f.input :price, priority: [ "9.99" ], collection: [ "0", "9.99", "19.99", "49.99", "99.99", "149.99", "199.99"], as: :radio_buttons
    = f.input :level, collection: [ "beginner", "intermediate", "advanced"], as: :radio_buttons
    = f.input :published

  .form-actions
    = f.button :submit, class: 'btn btn-md btn-primary'

app/views/trash/courses/edit.html.haml
.row
  .col-lg-3
  .col-lg-6
    .card
      .card-header
        %h4
          .fa.fa-graduation-cap
          Editing course
      .card-body
        = render 'form'
      .card-footer
        = link_to 'Cancel', @course

app/views/trash/courses/index.html.haml
/courses/index
- content_for :title do
  EDURGE
  |
  = action_name.humanize
  Courses

.text-center
  %h3.text-white
    .fa.fa-graduation-cap
    = action_name.humanize
    courses
    .badge.badge-danger= @courses.count

.card-columns
  - @courses.each do |course|
    = render 'courses/course', course: course

app/views/trash/courses/new.html.haml
.row
  .col-lg-3
  .col-lg-6
    .card
      .card-header
        %h4
          .fa.fa-graduation-cap
          New course
      .card-body
        = render 'form'
      .card-footer
        = link_to 'Cancel', root_path

app/views/trash/courses/show.html.haml
/course/show
- content_for :title do
  EDURGE
  |
  = @course.name

.text-white
  .fa.fa-bookmark
  = link_to @course.category, category_path(@course.category)
  >
  .fa.fa-graduation-cap
  = @course.name

.row
  .col-lg-8.order-1.order-lg-0
    .jumbotron
      %h3
        .fa.fa-graduation-cap
        %b= @course.name
      %p
      .fa.fa-clock
      Last updated
      = @course.updated_at.strftime('%m/%Y')
      .row
      .fa.fa-comment
      = @course.language
      .row
      .fa.fa-signal
      = @course.level
      .row
      .fa.fa-clock
      %b Duration:
      = @course.duration 
      min
      .row
      %b Price:
      = number_to_currency(@course.price)
      .row
      %b Description:
      %small= simple_format(@course.description)

    .text-white
      %h4
        .fa.fa-book
        = pluralize(@course.lessons_count, 'lesson')
        .float-right
          .fa.fa-spinner
          = number_to_percentage(@course.progress(current_user), precision: 0)
          /.progress
          /  .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "#{@course.progress(current_user)}", :role => "progressbar", :style => "width: #{@course.progress(current_user)}%;"} #{@course.progress(current_user).round(2)}%


    .list-group.lesson-sortable
      - @lessons.each do |lesson|
        = content_tag "div", id: "lesson-#{lesson.id}", data: { model_name: lesson.class.name.underscore, update_url: lesson_sort_path(lesson)} do
          .list-group-item
            = render 'lessons/lesson_preview', lesson: lesson
    %p
    .text-white
      %h4
        .fa.fa-comment
        = pluralize(@subscriptions.count, 'review')
    - @subscriptions.each do |subscription|
      = render 'subscriptions/subscription', subscription: subscription
      %p

  .col-lg-4.order-0.order-lg-1
    .sticky-top
      = render 'courses/course', course: @course
    %p