config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

      devise_scope :user do
    authenticated  do
      root 'courses#index'
    end
    unauthenticated do
      root 'home#index', as: :visitors_url
    end
  end 

  resources :categories
  resources :dashboard
  resources :courses do
    get :created, :purchased, :published_unapproved, :pending_review, :latest, :top_rated, :popular, on: :collection
    member do
  		patch :approve
  		patch :disapprove
    end
    resources :subscriptions, only: [:new, :create]
    resources :lessons do
      put :sort
    end
  end

  resources :subscriptions do
    get :my_students, on: :collection
    member do
  		patch :remove_review
    end
  end

  resources :users, only: [:show, :index]

  resources :lessons do
    put :sort
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    skip_before_action :authenticate_user!, :only => [:index]
  def index
    @latest_courses = Course.published.approved.order(created_at: :desc).limit(8)
    @top_rated_courses = Course.published.approved.order(average_rating: :desc, created_at: :desc).limit(3)
    @popular_courses = Course.published.approved.order(subscriptions_count: :desc, created_at: :desc).limit(3)
    @popular_categories = Category.all.order(courses_count: :desc).limit(3)
    @latest_good_subscriptions = Subscription.rated.order(rating: :desc, created_at: :desc).limit(3)
    @purchased_courses = Course.joins(:subscriptions).where(subscriptions: {user: current_user}).order(created_at: :desc).limit(3)
    @categories = Category.all.order('name ASC')
    @attente = Course.published.unapproved.order(updated_at: :desc)
    @nope_courses = Course.published.unapproved.order(created_at: :desc).limit(8)
  end
    def published_unapproved
    @courses = Course.published.unapproved.order(updated_at: :desc)
    authorize @courses, :approve?
    render 'index'
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_course.html.erb
<div class="card h-100">
  <%= image_tag course.thumbnail.url, class:"card-img-top" %>
  <div class="card-body">
    <h4><%= link_to course.name, course %></h4>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col-md-6">
        <div class="text-warning fa fa-star"></div>
        <p><b><%= course.average_rating %></b></p>
        <p><%=course.subscriptions_count%> <span class="fa fa-user-graduate"></span></p>
      </div>
      <div class="col-md-6 text-right">
        <div class="fa fa-chalkboard-teacher"></div>
        <%= link_to course.user.username, user_path(course.user) %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="text-center">
      <!--logic in courses_helper.rb
      -->
      <%= subscription_buttons(course) %>
      <div class="row"></div>
      <%= review_buttons(course) %>
      <!--- if course.bought(current_user) == false
      -->
      <!--  Bought
      -->
      <!--- else
      -->
      <!--  Buy
      -->
    </div>
  </div>
  <% if current_user %>
    <% if policy(course).edit? %>
      <div class="card-footer">
        <%= link_to 'Add a lesson', new_course_lesson_path(course, @lesson), class: 'btn btn-sm btn-primary' %>
        <%= link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning' %>
        <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
      </div>
    <% end %>
    <% if policy(course).destroy? %>
      <div class="card-footer">
        <% if course.published? %>
          <div class="badge badge-success">
            published
          </div>
        <% else %>
          <div class="badge badge-danger">
            published
          </div>
        <% end %>
        <% if course.approved? %>
          <div class="badge badge-success">
            approved
          </div>
        <% else %>
          <div class="badge badge-danger">
            approved
          </div>
        <% end %>
      </div>
    <% end %>
    <% if policy(course).approve? %>
      <div class="card-footer">
        <% if course.approved? %>
          <%= link_to 'Disapprove', disapprove_course_path(course), method: :patch, class: 'btn btn-sm btn-primary' %>
        <% else %>
          <%= link_to 'Approve', approve_course_path(course), method: :patch, class: 'btn btn-sm btn-primary' %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<div class="container-fluid top-menu text-white">
  <div class="row p-2">
    <div class="col-lg-2">
      <h5>Afripédia</h5>
    </div>
    <div class="col-lg-5">
      <%= form_tag(courses_path, class:"row row-cols-lg-auto g-3 align-items-center", method: :get) do %>
            <div class="input-group mb-3">
              <%= text_field_tag :name, params[:name], autocomplete: 'off', placeholder: "Trouver un cours", class: 'form-control' %>
                <button class="btn btn-primary" type="submit">
                  Trouver un cours
                </button>
            </div>
          <% end %>
    </div>
    <div class="col-lg-5">
     <%=render 'menus/admin'%>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-12">
      <h3>récents</h3>
<div class="row row-cols-1 row-cols-md-4 g-4">
  <% @latest_courses.each do |course| %>
  <div class="col">
    <div class="card h-100">
    <%= render 'dashboard/course', course: course %>
    </div>
</div>
<% end %>
</div>
    </div>
     <div class="col-lg-12 col-12">
      <h3>populaires</h3>
      <div class="row row-cols-1 row-cols-md-4 g-4">
          <% @popular_courses.each do |course| %>
  <div class="col">
        <%= render 'dashboard/course', course: course %>
  <% end %>
  </div>
</div>
    </div>
    <div class="col-lg-12 col-12">
      <h3>mieux notés</h3>
      <div class="row row-cols-1 row-cols-md-4 g-4">
          <% @top_rated_courses.each do |course| %>
  <div class="col">
        <%= render 'dashboard/course', course: course %>
  <% end %>
  </div>
</div>
    </div>
        <div class="col-lg-12 col-12">
      <h3>mieux notés</h3>
      <div class="row row-cols-1 row-cols-md-4 g-4">
          <% @nope_courses.each do |course| %>
  <div class="col">
        <%= render 'dashboard/course', course: course %>
  <% end %>
  </div>
</div>
    </div>
  </div>
</div>