config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

      devise_scope :user do
    authenticated  do
      root 'courses#index'
    end
    unauthenticated do
      root 'home#index', as: :visitors_url
    end
  end 

  resources :categories
  resources :dashboard
  resources :courses do
    get :created, :purchased, :published_unapproved, :pending_review, :latest, :top_rated, :popular, on: :collection
    member do
  		patch :approve
  		patch :disapprove
    end
    resources :subscriptions, only: [:new, :create]
    resources :lessons do
      put :sort
    end
  end

  resources :subscriptions do
    get :my_students, on: :collection
    member do
  		patch :remove_review
    end
  end

  resources :users, only: [:show, :index]

  resources :lessons do
    put :sort
  end

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  #belongs_to :user, counter_cache: true #counter_cache not working here for some reason
  belongs_to :course, counter_cache: true

  scope :pending_review, -> { where(rating: [0, nil, ""], comment: [nil, ""]) }
  scope :rated, -> { where.not(comment: [nil, ""]) }

  validates :user, :course, presence: true

  validates_presence_of :rating, if: :comment?
  validates_presence_of :comment, if: :rating?

  validates_uniqueness_of :user_id, scope: :course_id  #user cant be subscribed to the same course twice
  validates_uniqueness_of :course_id, scope: :user_id  #user cant be subscribed to the same course twice
  
  validate :cant_subscribe_to_own_course  #user can't create a subscription if course.user == current_user.id
  protected
  def cant_subscribe_to_own_course
    if self.new_record?
      if user_id == course.user_id
        errors.add(:base, "You can not subscribe to your own course")
      end
    end
  end

  after_destroy do
    course.update_rating
  end

  after_save do
    unless rating.nil? || rating.zero?
      course.update_rating
    end 
  end 
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy, :remove_review]
  before_action :set_course, only: [:new, :create]

  def index
    @subscriptions = Subscription.all.order(created_at: :desc)
    authorize @subscriptions
  end
  
  def my_students
    @subscriptions = Subscription.joins(:course).where(courses: {user: current_user}).order(created_at: :desc)
    #authorize @subscriptions, :mine?
    render 'index'
  end

  def remove_review
    authorize @subscription, :edit?
		@subscription.update_attributes(rating: nil, comment: nil)
		@subscription.course.update_rating
		redirect_to @subscription.course, alert: "Review removed"
  end

  def show
  end

  def new
    #@subscription = Subscription.new
  end

  def edit
    authorize @subscription
  end

  def create
    if @course.price > 0
      flash[:alert] = "You can not access paid courses yet."
      redirect_to new_course_subscription_path(@course)
    else
      @subscription = current_user.buy_course(@course)
      redirect_to course_path(@course), notice: 'You bought the course!'
    end

    #@subscription = current_user.buy_course(@course)
    #respond_to do |format|
    #  format.html {redirect_to course_path(@course), notice: 'You bought the course!'}
    #end

    #@subscription = Subscription.new(subscription_params)
    #respond_to do |format|
    #  if @subscription.save
    #    format.html { redirect_to @subscription.course, notice: 'Subscription was successfully created.' }
    #    #format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully created.' }
    #    format.json { render :show, status: :created, location: @subscription }
    #  else
    #    format.html { render :new }
    #    format.json { render json: @subscription.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  def update
    authorize @subscription
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to course_path(@subscription.course), notice: 'Review was successfully posted. Thank you!' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @subscription
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'User course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    def set_course
      @course = Course.friendly.find(params[:course_id])
    end

    def subscription_params
      params.require(:subscription).permit(:rating, :comment)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<% # frozen_string_literal: true %>
<%= simple_form_for(@subscription) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <% unless f.object.new_record? %>
      <%= f.input :rating, collection: 1..5, as: :radio_buttons %>
      <%= f.input :comment, input_html: { autocomplete: 'nope' }, :input_html => {:rows => 7} %>
    <% else %>
      <h4>
        <%= number_to_currency(@course.price) %>
      </h4>
    <% end %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-md btn-primary' %>
    <!--= f.submit 'Subscribe', class: 'btn btn-md btn-primary'
    -->
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<div class="card">
  <div class="card-header">
    <div class="fa fa-user"></div>
    <%= link_to subscription.user.username, user_path(subscription.user) %>
    <div class="fa fa-clock"></div>
    <%= time_ago_in_words(subscription.created_at) %>
    ago
    <!--= subscription.created_at.strftime('%d/%b/%Y')
    -->
    <div class="fa fa-graduation-cap"></div>
    <%= link_to subscription.course, course_path(subscription.course) %>
  </div>
  <div class="card-footer">
    <div class="text-warning fa fa-star"></div>
    <b>
      <%= subscription.rating %>
    </b>
    <div class="fa fa-comment"></div>
    <small>
      <%= subscription.comment %>
    </small>
  </div>
  <% if current_user %>
    <div class="card-footer">
      <% if policy(subscription).edit? %>
        <%= link_to 'Edit', edit_subscription_path(subscription), class: 'btn btn-sm btn-primary' %>
        <%= link_to 'Remove', remove_review_subscription_path(subscription), method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/subscriptions/edit.html.erb
<div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        <h4>
          <div class="fa fa-graduation-cap"></div>
          <%= link_to @subscription.course.name, course_path(@subscription.course) %>
          <hr/>
          <div class="text-warning fa fa-star"></div>
          Add a Review
        </h4>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
      <div class="card-footer">
        <%= link_to 'Cancel', course_path(@subscription.course) %>
      </div>
    </div>
  </div>
</div>

app/views/subscriptions/index.html.erb
<div class="text-center text-white">
  <h3>
    <div class="fa fa-lock-open"></div>
    <%= action_name.humanize + ":" %>
    <%= pluralize(@subscriptions.count, 'subscription') %>
  </h3>
</div>
<p></p>
<table id="table1">
  <thead>
    <tr>
      <th>
        <div class="fa fa-user"></div>
        user
      </th>
      <th>
        <div class="fa fa-envelope"></div>
        email
      </th>
      <th>
        <div class="fa fa-clock"></div>
        <div class="fa fa-lock-open"></div>
        bought
      </th>
      <th>
        <div class="fa fa-graduation-cap"></div>
        course
      </th>
      <th>
        <div class="fa fa-dollar-sign"></div>
        paid
      </th>
      <th>
        <div class="fa fa-spinner"></div>
        progress
      </th>
      <th>
        <div class="text-warning fa fa-clock"></div>
        reviewed
      </th>
      <th>
        <div class="text-warning fa fa-star"></div>
        rating
      </th>
      <th>
        <div class="text-warning fa fa-comment"></div>
        feedback
      </th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td>
          <%= link_to subscription.user, user_path(subscription.user) %>
        </td>
        <td>
          <%= subscription.user.email %>
        </td>
        <td>
          <%= subscription.created_at.strftime('%d/%b/%Y') %>
        </td>
        <td>
          <%= link_to subscription.course, course_path(subscription.course) %>
        </td>
        <td>
          <%= number_to_currency(subscription.price) %>
        </td>
        <td>
          <%= number_to_percentage(subscription.course.progress(subscription.user), precision: 0) %>
        </td>
        <td>
          <% if subscription.rating.present? %>
            <%= subscription.updated_at.strftime('%d/%b/%Y') %>
          <% end %>
        </td>
        <td>
          <%= subscription.rating %>
        </td>
        <td>
          <%= subscription.comment %>
        </td>
        <td>
          <% if policy(subscription).edit? %>
            <%= link_to 'Review', edit_subscription_path(subscription) %>
          <% end %>
        </td>
        <td>
          <% if policy(subscription).destroy? %>
            <%= link_to 'Unsubscribe', subscription, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<p></p>

app/views/subscriptions/new.html.erb
<div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        <h4>
          <div class="fa fa-graduation-cap"></div>
          <%= link_to @course.name, course_path(@course) %>
          <hr/>
          <div class="fa fa-lock-open"></div>
          Buy course
        </h4>
      </div>
      <div class="card-body">
        <%= form_tag course_subscriptions_path(@course) do %>
          <%= submit_tag "Pay #{@course.price} &euro;".html_safe, class: "btn btn-success btn-md btn-block" %>
        <% end %>
      </div>
      <div class="card-footer">
        <%= link_to 'Cancel', course_path(@course) %>
      </div>
    </div>
  </div>
</div>

app/views/subscriptions/show.html.erb
<%= render 'subscriptions/subscription', subscription: @subscription %>